### ISSUE TITLE
Soundpool für Chat-Schnellreaktionen

### ISSUE THREAD

**Issue by julihuber0** [julihuber0/Wizard#5]
Hinzufügen von mehreren Sounds für die Schnellreaktionen im Chat, damit mehr Abwechslung entsteht.

**Comment by DragonFire7** [comment]
Ich hätte ne Idee:
Soundfiles alle nach gleichem Schema benennen z.B. zefix_1.wav zefix_2.wav usw.

Beim Start des Programms: Für jede Schnellreaktion am Anfang einmal auslesen, bis zu welcher Nummer die Files existieren, dann die Nummer speichern

Bei Anweisung, dass sound abgespielt werden soll: Den String zusammensetzen mit einer Zufallszahl <= Nummer an Files

**Comment by DragonFire7** [comment]
Dadurch könnten wir unterschiedliche Soundpacks anbieten

**Comment by julihuber0** [comment]
Evtl. auch gleich im Startscreen eine Dropdown-Liste anbieten, wo das entsprechende Soundpack gleich ausgewählt werden kann.

**Comment by julihuber0** [comment]
Ich hab jetzt mal im Branch "soundpacks" alles soweit vorbereitet, dass man verschiedene Soundpacks in Unterordnern vom Resources Ordner anlegen kann, dazu gibt es in GUINew eine neue statische Konstante (String-Array), in welchem sämtliche Packnamen/Ordnernamen eingetragen sind, wird dann automatisch in allen entsprechenden JComboBoxen übernommen und in der Utility Klasse bei der "playSound"-Methode berücksichtigt.

@DragonFire7 
>> Soundfiles alle nach gleichem Schema benennen z.B. zefix_1.wav zefix_2.wav usw.

Da müssen dann erst mal so viele verschiedene Sounds gefunden werden, ist tatsächlich schwieriger, als man meint, da was Passendes zu finden.

>> Bei Anweisung, dass sound abgespielt werden soll: Den String zusammensetzen mit einer Zufallszahl <= Nummer an  Files

Da müssten wir dann wahrscheinlich aber für jeden Sound eine eigene Grenze für die Zufallszahl finden, da wir unwahrscheinlich für jede Schnellreaktion gleich viele Sounds finden werden.
